name: DEV Manual Infrastructure Destroy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - destroy

env:
  GITHUB_PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
jobs:
  plan-networking:
    runs-on: ubuntu-latest
    needs: [destroy-cluster]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git access
        run: |
          git config --global url."https://${GITHUB_PAT_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Terraform Init (Networking)
        run: terraform init
        working-directory: dev/networking

      - name: Terraform Destroy Plan (Networking)
        run: terraform plan -destroy -no-color -out=tfplan
        working-directory: dev/networking

      - name: Upload Terraform Plan Destroy (Networking)
        uses: actions/upload-artifact@v2
        id: upload
        with:
          name: tfplan
          path: dev/networking/tfplan 

  destroy-networking:
    runs-on: ubuntu-latest
    needs: [plan-networking]
    if: ${{ github.event.inputs.action == 'destroy' }}
    environment:
      name: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git access
        run: |
          git config --global url."https://${GITHUB_PAT_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Download Terraform Plan Destroy (Networking)
        uses: actions/download-artifact@v2
        with:
          name: tfplan
          path: dev/networking

      - name: Terraform Destroy (Networking)
        working-directory: dev/networking
        run: |
          terraform init
          terraform apply -auto-approve tfplan

  plan-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git access
        run: |
          git config --global url."https://${GITHUB_PAT_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Terraform Init (Cluster)
        run: terraform init
        working-directory: dev/cluster

      - name: Terraform Destroy Plan (Cluster)
        run: terraform plan -destroy -no-color -out=tfplan
        working-directory: dev/cluster

      - name: Upload Terraform Plan Destroy (Cluster)
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: dev/cluster/tfplan

  destroy-cluster:
    runs-on: ubuntu-latest
    needs: [plan-cluster]
    if: ${{ github.event.inputs.action == 'destroy' }}
    environment:
      name: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git access
        run: |
          git config --global url."https://${GITHUB_PAT_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Download Terraform Plan Destroy (Cluster)
        uses: actions/download-artifact@v2
        with:
          name: tfplan
          path: dev/cluster

      - name: Terraform Destroy (Cluster)
        working-directory: dev/cluster
        run: |
          terraform init
          terraform apply -auto-approve tfplan
